# SEE docker-compose-withenvoy.yml
# https://blog.logrocket.com/containerized-development-nestjs-docker/
# This is used by yarn start:deps:indocker
version: '3.7'

services:
  envoy:
    container_name: ecoloop-envoy-onprem
    image: envoyproxy/envoy-dev:a240824c376693b16ca8be51e435b95c42f3449f
    depends_on:
      - ecoloop-web
      - ecoloop-server
    networks:
      - webnet
    ports:
      - "9901:9901"
      - "${PROXY_EXPOSE_PORT}:80"
    volumes:
      - ${ENVOY_FILE}:/etc/envoy/envoy.yaml

  ecoloop-server:
    container_name: ecoloop-server-onprem
    image: hanalooper/ecoloop-server:0.18.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    command: >
      sh -c "./wait-for.sh postgres:5432 -- npx prisma migrate deploy"
    env_file:
      - .env.docker-server
    networks:
      - webnet
    depends_on:
      - postgres
      - ecoloop-ml
      # - minio
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres-onprem
    # command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8' COMMENTED OUT AS prisma db:migrate is failing (maybe since pg 15 ??)
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  # Use FS for local test
  # minio:
  #   image: 'bitnami/minio:latest'
  #   container_name: el-minio-test
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   environment:
  #     - MINIO_ROOT_USER=minio-root-user
  #     - MINIO_ROOT_PASSWORD=minio-root-password
  #   networks:
  #     - webnet
  ecoloop-ml:
    image: hanalooper/ecoloop-ml:latest
    container_name: ecoloop-ml-onprem
    ports:
      - 9090:9090
    networks:
      - webnet
  ecoloop-web:
    container_name: ecoloop-web-onprem
    image: hanalooper/ecoloop-web:0.18.0
    env_file:
      - .env.docker-web
    networks:
      - webnet
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    depends_on:
      - ecoloop-server

networks:
  webnet:
volumes:
  pgdata:
